### ISSUE TITLE
error when evaluating

### ISSUE THREAD

**Issue by txAnnie** [shayneobrien/coreference-resolution#9]
Evaluating on validation corpus...
217it [12:27,  5.54s/it]Traceback (most recent call last):
  File "./src/coref.py", line 690, in <module>
    trainer.train(150)
  File "./src/coref.py", line 467, in train
    results = self.evaluate(self.val_corpus)
  File "./src/coref.py", line 566, in evaluate
    predicted_docs = [self.predict(doc) for doc in tqdm(val_corpus)]
  File "./src/coref.py", line 566, in <listcomp>
    predicted_docs = [self.predict(doc) for doc in tqdm(val_corpus)]
  File "./src/coref.py", line 595, in predict
    spans, probs = self.model(doc)
  File "/home/xtan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    tracing_state._traced_module_stack.append(self)
  File "./src/coref.py", line 429, in forward
    spans, coref_scores = self.score_pairs(spans, g_i, mention_scores)
  File "/home/xtan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    tracing_state._traced_module_stack.append(self)
  File "./src/coref.py", line 347, in forward
    pairs = torch.cat((i_g, j_g, i_g*j_g, phi), dim=1)
RuntimeError: CUDA error: out of memory

I got this error when evaluating on validation corpus.

**Comment by txAnnie** [comment]
I used GPU to train.

**Comment by gaoya-J** [comment]
I got this error when evaluating on validation corpus.
